MOSIP-25219: Renamed project and moved to repo
mosip/esignet-mock-services pull request #1
Opened 2023-01-19 07:00 UTC by HimajaDhanyamraju2

2023-01-23 15:49 UTC, vishwa-vyom requested changes

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/java/io/mosip/mock/identity/system/controller/MockIdentityController.java
> +	@PostMapping(value = "mock-identity", consumes = { MediaType.APPLICATION_JSON_VALUE }, produces = {
Lets rename this to just identity in the URL.
Lets also change the controller and service names to IdentityController, IdentityService, IdentityRepository etc..

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/java/io/mosip/mock/identity/system/controller/MockIdentityController.java
> +		mockAuthDataResponse.setStatus("mock auth data created successfully");
this is mock id data and not auth data

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/java/io/mosip/mock/identity/system/dto/Values.java
> +public class Values {
Lets rename this to LanguageValue

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/java/io/mosip/mock/identity/system/controller/MockIdentityController.java
> +	public ResponseWrapper<MockAuthData> getMockIdentity(@PathVariable(value = "virtual-id") String virtualId)
Lets rename virtualId to individualId everywhere in the code

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/java/io/mosip/mock/identity/system/dto/MockAuthData.java
> +public class MockAuthData {
Lets name this to IdentityData

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/java/io/mosip/mock/identity/system/dto/BiometricProperties.java
> +public class BiometricProperties {
Lets rename this to BiometricData

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/java/io/mosip/mock/identity/system/dto/MockAuthDataResponse.java
> +public class MockAuthDataResponse {
Lets rename this to IdentityStatus

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/java/io/mosip/mock/identity/system/service/MockIdentityService.java
> +	public void saveIdentity(MockAuthData mockAuthDataRequest) throws MockIdentityException;
Lets rename this to addIdentity

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/java/io/mosip/mock/identity/system/service/impl/MockIdentityServiceImpl.java
> +		mockIdentityRepository.save(mockIdentity);
In this POST endpoint, we should not allow updates, only unique individualId creates should work. If there is duplicate, we have to return with respective error in response.

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/java/io/mosip/mock/identity/system/util/MockIdentityUtil.java
> +public class MockIdentityUtil {
Lets rename this to HelperUtil

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/java/io/mosip/mock/identity/system/util/MockIdentityUtil.java
> +	public static String getUTCDateTime() {
rename this to getCurrentUTCDateTime

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/java/io/mosip/mock/identity/system/validator/RequestTimeValidator.java
> +    private int minMinutes;
Can we take the above 2 configs as a single config called "esignet.mock.identity-system.allowed-request-time-variation-seconds" and do both + and - case.

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/resources/bootstrap.properties
> +registration.processor.queue.url=localhost
why do we need the above 3 properties ?

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/main/resources/dbscripts.sql
> +alter table "mockidentitysystem"."mock_identity" add constraint "pk_mock_id_code" primary key ("individual_id");
db scripts are not suppose to be outside ?

2023-01-23 15:49 UTC, vishwa-vyom commented on mock-identity-system/src/test/java/io/mosip/mock/identity/system/MockIdentitySystemApplicationTest.java
> +{
Can we also add a few integration test scenarios which will test end to end scenarios

2023-02-01 09:44 UTC, ase-101 commented on db_scripts/mosip_mockidentitysystem/drop_role.sql
> +drop role if exists idpuser;
Rename this to mockidentitysystemuser

2023-02-01 09:45 UTC, ase-101 commented on db_scripts/mosip_mockidentitysystem/grants.sql
> +   TO idpuser;
Rename this to mockidsystemuser

2023-02-01 09:45 UTC, ase-101 commented on db_scripts/mosip_mockidentitysystem/grants.sql
> +   TO idpuser;
Rename this to mockidsystemuser

2023-02-01 09:45 UTC, ase-101 commented on db_scripts/mosip_mockidentitysystem/grants.sql
> +   TO idpuser;
Rename this to mockidsystemuser

2023-02-01 09:45 UTC, ase-101 commented on db_scripts/mosip_mockidentitysystem/grants.sql
> +	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO idpuser;
Rename this to mockidsystemuser

2023-02-01 09:51 UTC, ase-101 commented on mock-identity-system/src/main/java/io/mosip/esignet/mock/identitysystem/MockIdentitySystemApplication.java
> +@SpringBootApplication(scanBasePackages = { "io.mosip.mock.identity.system" })
seems like the scanbase package name is incorrect @HimajaDhanyamraju2 
it should be io.mosi.esignet.mock

2023-02-01 09:55 UTC, ase-101 commented on mock-identity-system/src/main/java/io/mosip/esignet/mock/identitysystem/dto/IdentityData.java
> +	@NotBlank(message = ErrorConstants.INVALID_INDIVIDUAL_ID)
Pls, correct the error constant.

2023-02-02 18:38 UTC, vishwa-vyom commented
Merging the PR based on Anusha's request.

2023-02-02 18:39 UTC, merged